# Change these first
owner: luke-beep # Your GitHub organization or username, where this repository lives
repo: status.voltflx.com # The name of this repository

sites:
  - name: VOLTFLX
    url: https://voltflx.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voltflx.com
  logoUrl: https://github.com/luke-beep/status.voltflx.com/blob/master/assets/asset.svg
  name: VoltFLX Status Page
  introTitle: "VoltFLX Log Status"
  introMessage: "Welcome to VoltFLX Status Page!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/luke-beep/status.voltflx.com
    - title: Website
      href: https://voltflx.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
